// demo/global-state-angular/src/app/parent/demo/demo.component.ts
import { Component } from '@angular/core';
import dataSource from '~/dataSource';

@Component({
  selector: 'demo',
  template: `
    <p style="border: solid 1px blue">
      demo 
      <button (click)="tick()">count {{dataSource.count}}</button>
      <child-a></child-a>
      <child-b></child-b>
    </p>
  `,
  styles: []
})
export class DemoComponent {
  dataSource = dataSource;

  tick() {
    this.dataSource.tick();
  }

  ngAfterViewChecked() {
    console.log('demo view checked')
  }
}

// demo/global-state-react/src/App/Parent/Demo/Demo.tsx
import React from 'react';
import { useContext } from 'react';
// import dataSource from 'src/App/dataSource';
import { StoreAContext } from 'src/App/storeA';
import ChildA from './ChildA/ChildA';
import ChildB from './ChildB/ChildB';

function Demo() {
  const storea = useContext<any>(StoreAContext);

  console.log('Demo render');

  return (
    <div style={{ border: 'solid 1px blue' }}>
      Demo
      <button onClick={() => storea.tick()}>storea.count {storea.data.count}</button>
      <ChildA />
      <ChildB />
    </div>
  );
}

export default Demo;
