// demo/global-state-vue/src/components/Demo.vue
<template>
  <div style="border: solid 1px blue">
    Demo
    <button @click="dataSource.tick()">count {{ dataSource.count }}</button>
    <ChildA />
    <ChildB />
  </div>
</template>

<script>
import dataSource from "../dataSource";
import ChildA from "./ChildA.vue";
import ChildB from "./ChildB.vue";

export default {
  data() {
    return { dataSource };
  },
  components: {
    ChildA,
    ChildB,
  },
};
</script>

// demo/global-state-react/src/App/Parent/Demo/Demo.tsx
import React from 'react';
import { useContext } from 'react';
// import dataSource from 'src/App/dataSource';
import { StoreAContext } from 'src/App/storeA';
import ChildA from './ChildA/ChildA';
import ChildB from './ChildB/ChildB';

function Demo() {
  const storea = useContext<any>(StoreAContext);

  console.log('Demo render');

  return (
    <div style={{ border: 'solid 1px blue' }}>
      Demo
      <button onClick={() => storea.tick()}>storea.count {storea.data.count}</button>
      <ChildA />
      <ChildB />
    </div>
  );
}

export default Demo;
