// demo/global-state-react/src/App/Parent/Demo/ChildA/ChildA.tsx
import React, { useContext } from 'react';
// import dataSource from 'src/App/dataSource';
import { StoreCContext } from 'src/App/storeC';

function ChildA() {
  const storec = useContext<any>(StoreCContext);

  console.log('ChildA render');
  return (
    <div>
      ChildA
      <button onClick={() => storec.tick()}>storec.count {storec.data.count}</button>
    </div>
  );
}

export default ChildA;

// demo/global-state-angular/src/app/parent/demo/child-a/child-a.component.ts
import { Component } from '@angular/core';
import dataSource from '~/dataSource';

@Component({
  selector: 'child-a',
  template: `
    <p>
      child-a
      <button (click)="tick()">count {{dataSource.count}}</button>
    </p>
  `,
  styles: []
})
export class ChildAComponent {
  dataSource = dataSource;

  tick() {
    this.dataSource.tick();
  }

  ngAfterViewChecked() {
    console.log('child-a view checked')
  }
}
