// demo/global-state-react/src/App/Parent/Sibling/Sibling.tsx
import React, { useContext } from 'react';
// import dataSource from 'src/App/dataSource';
import { StoreAContext } from 'src/App/storeA';

function Sibling() {
  const storea = useContext<any>(StoreAContext);

  console.log('Sibling render');

  return (
    <div>
      Sibling
      <button onClick={() => storea.tick()}>storea.count {storea.data.count}</button>
    </div>
  );
}

export default Sibling;

// demo/global-state-angular/src/app/parent/sibling/sibling.component.ts
import { Component } from '@angular/core';
import dataSource from '~/dataSource';

@Component({
  selector: 'sibling',
  template: `
    <p>
      sibling
      <button (click)="tick()">count {{dataSource.count}}</button>
    </p>
  `,
  styles: []
})
export class SiblingComponent {

  dataSource = dataSource;

  tick() {
    this.dataSource.tick();
  }

  ngAfterViewChecked() {
    console.log('sibling view checked')
  }
}
