// demo/global-state-angular/src/app/other-parent/other-parent.component.ts
import { Component } from '@angular/core';
import dataSource from '~/dataSource';

@Component({
  selector: 'other-parent',
  template: `
    <p>
      other-parent
      <button (click)="tick()">count {{dataSource.count}}</button>
    </p>
  `,
  styles: []
})
export class OtherParentComponent {
  dataSource = dataSource;

  tick() {
    this.dataSource.tick();
  }

  ngAfterViewChecked() {
    console.log('other-parent view checked')
  }

}

// demo/global-state-react/src/App/OtherParent/OtherParent.tsx
import React from 'react';
import dataSource from '../dataSource';

function OtherParent() {

  console.log('OtherParent render');

  return (
    <div>
      OtherParent
      <button onClick={() => dataSource.tick()}>count {dataSource.count}</button>
    </div>
  );
}

export default OtherParent;
