// react-demo/src/Feed.tsx
import React from 'react';
import { useState } from 'react';
import logger from './logger';

function App({ item }: { item: any }) {
  const [itemData, setItemData] = useState(item);

  const logTime = (sign: string, fnReturn?: any) => {
    logger(sign);
  }

  const toggle = () => {
    itemData.isShowComment = !itemData.isShowComment;
    setItemData({ ...itemData });
  }

  const favorite = () => {
    itemData.favorite += 1;
    setItemData({ ...itemData });
  }

  const like = () => {
    itemData.like += 1;
    setItemData({ ...itemData });
  }

  const forward = () => {
    itemData.forward += 1;
    setItemData({ ...itemData });
  }

  const comment = () => {
    itemData.comments.push({
      id: itemData.id + 10000 + itemData.comments.length,
      content: itemData.newComment
    });
    itemData.newComment = '';
    setItemData({ ...itemData });
  }


  return (
    <>
      <div>{itemData.author + itemData.id} :</div>
      <div>{itemData.content}</div>
      <div>
        <button className="btn" onClick={() => logTime('favorite', favorite())}>favorite {itemData.favorite || ''}</button>
        <button className="btn" onClick={() => logTime('like', like())}>like {itemData.like || ''}</button>
        <button className="btn" onClick={() => logTime('forward', forward())}> forward {itemData.forward || ''}</button >
        <button className="btn" onClick={() => logTime('toggle', toggle())}> comment {itemData.comments.length || ''}</button >
      </div >
      {
        itemData.isShowComment && (
          <div>
            <input type="text" value={itemData.newComment} onChange={(e) => {
              itemData.newComment = e.target.value;
              setItemData({ ...itemData });
            }} />
            <button onClick={() => logTime('comment', comment())} disabled={!itemData.newComment}> ok</button >
            {
              itemData.comments.map((comment: any) => {
                return (
                  <div key={comment.id}>
                    {comment.content}
                  </div>
                )
              })
            }
          </div>
        )
      }
    </>
  );
}

export default App;

// angular-demo/src/app/feed/feed.component.ts
import { Component, OnInit, Input, NgZone } from '@angular/core';
import logger from '../logger';
import { first } from 'rxjs/operators';

@Component({
  selector: 'app-feed',
  template: `
    <div>{{item.author + item.id}} :</div>
    <div>{{item.content}}</div>
    <div>
      <button class="btn" (click)="logTime('favorite',favorite())">favorite {{item.favorite || ''}}</button>
      <button class="btn" (click)="logTime('like',like())">like {{item.like || ''}}</button>
      <button class="btn" (click)="logTime('forward',forward())">forward {{item.forward || ''}}</button>
      <button class="btn" (click)="logTime('toggle',toggle())">comment {{item.comments.length || ''}}</button>
    </div>
    <div *ngIf="item.isShowComment">
      <input type="text" [(ngModel)]="item.newComment" />
      <button (click)="logTime('comment',comment())" [disabled]="!item.newComment">ok</button>
      <div *ngFor="let comment of item.comments; trackBy: trackById" >{{comment.content}}</div>
    </div>
  `,
  styles: [
  ]
})
export class FeedComponent {
  @Input() public item: any;

  constructor(private ngZone: NgZone) { }

  logTime(sign: string, fnReturn?: any) {
    this.ngZone.runOutsideAngular(() => {
      logger(sign);
    });
  }

  toggle() {
    this.item.isShowComment = !this.item.isShowComment;
  }

  favorite() {
    this.item.favorite += 1;
  }

  like() {
    this.item.like += 1;
  }

  forward() {
    this.item.forward += 1;
  }

  comment() {
    this.item.comments.push({
      id: this.item.id + 10000 + this.item.comments.length,
      content: this.item.newComment
    });
    this.item.newComment = "";
  }

  trackById(comment: any) {
    return comment.id;
  }
}
