// react-demo/src/Feed.tsx
import React from 'react';
import { useState } from 'react';
import logger from './logger';

function App({ item }: { item: any }) {
  const [itemData, setItemData] = useState(item);

  const toggle = () => {
    logger('toggle');
    itemData.isShowComment = !itemData.isShowComment;
    setItemData({ ...itemData });
  }

  const favorite = () => {
    logger('favorite');
    itemData.favorite += 1;
    setItemData({ ...itemData });
  }

  const like = () => {
    logger('like');
    itemData.like += 1;
    setItemData({ ...itemData });
  }

  const forward = () => {
    logger('forward');
    itemData.forward += 1;
    setItemData({ ...itemData });
  }

  const comment = () => {
    logger('comment');
    itemData.comments.push({
      id: itemData.id + 10000 + itemData.comments.length,
      content: itemData.newComment
    });
    itemData.newComment = '';
    setItemData({ ...itemData });
  }


  return (
    <>
      <div>{itemData.author + itemData.id} :</div>
      <div>{itemData.content}</div>
      <div>
        <button className="btn" onClick={() => favorite()}>favorite {itemData.favorite || ''}</button>
        <button className="btn" onClick={() => like()}>like {itemData.like || ''}</button>
        <button className="btn" onClick={() => forward()}> forward {itemData.forward || ''}</button >
        <button className="btn" onClick={() => toggle()}> comment {itemData.comments.length || ''}</button >
      </div >
      {
        itemData.isShowComment && (
          <div>
            <input type="text" value={itemData.newComment} onChange={(e) => {
              itemData.newComment = e.target.value;
              setItemData({ ...itemData });
            }} />
            <button onClick={() => comment()} disabled={!itemData.newComment}> ok</button >
            {
              itemData.comments.map((comment: any) => {
                return (
                  <div key={comment.id}>
                    {comment.content}
                  </div>
                )
              })
            }
          </div>
        )
      }
    </>
  );
}

export default App;

// vue-demo/src/components/Feed.vue
<template>
  <div>
    <div>{{itemData.author + itemData.id}} :</div>
    <div>{{itemData.content}}</div>
    <div>
      <button class="btn" @click="logger('favorite',favorite())">favorite {{itemData.favorite || ''}}</button>
      <button class="btn" @click="logger('like',like())">like {{itemData.like || ''}}</button>
      <button class="btn" @click="logger('forward',forward())">forward {{itemData.forward || ''}}</button>
      <button class="btn" @click="logger('toggle',toggle())">comment {{itemData.comments.length || ''}}</button>
    </div>
    <div v-if="itemData.isShowComment">
      <input type="text" v-model="itemData.newComment" />
      <button @click="logger('comment',comment())" :disabled="!itemData.newComment">ok</button>
      <div v-for="comment of itemData.comments" :key="comment.id">{{comment.content}}</div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import logger from "../logger";

export default defineComponent({
  props: ['item'],
  data() {
    return {
      itemData: this.item,
      logger
    };
  },
  methods: {
    toggle() {
      this.itemData.isShowComment = !this.itemData.isShowComment;
    },

    favorite() {
      this.itemData.favorite += 1;
    },

    like() {
      this.itemData.like += 1;
    },

    forward() {
      this.itemData.forward += 1;
    },

    comment() {
      this.itemData.comments.push({
        id: this.itemData.id + 10000 + this.itemData.comments.length,
        content: this.itemData.newComment
      });
      this.itemData.newComment = "";
    }
  }
});
</script>
