// demo/global-state-react/src/App/Parent/Parent.tsx
import React from 'react';
import dataSource from '../dataSource';
import Demo from './Demo/Demo';
import Sibling from './Sibling/Sibling';

function Parent() {
  console.log('Parent render');

  return (
    <div style={{ border: 'solid 1px red' }}>
      Parent
      <button onClick={() => dataSource.tick()}>count {dataSource.count}</button>
      <Demo />
      <Sibling />
    </div>
  );
}

export default Parent;

// demo/global-state-vue/src/components/Parent.vue
<template>
  <div style="border: solid 1px red">
    Parent
    <button @click="dataSource.tick()">count {{ dataSource.count }}</button>
    <Demo />
    <Sibling />
  </div>
</template>

<script>
import dataSource from "../dataSource";
import Demo from "./Demo.vue";
import Sibling from "./Sibling.vue";

export default {
  data() {
    return { dataSource };
  },
  components: {
    Demo,
    Sibling,
  },
};
</script>
