// demo/global-state-angular/src/app/parent/parent.component.ts
import { Component } from '@angular/core';
import dataSource from '~/dataSource';

@Component({
  selector: 'parent',
  template: `
    <p style="border: solid 1px red;">
      parent
      <button (click)="tick()">count {{dataSource.count}}</button>
      <demo></demo>
      <sibling></sibling>
    </p>
  `,
  styles: []
})
export class ParentComponent {

  dataSource = dataSource;

  tick() {
    this.dataSource.tick();
  }

  ngAfterViewChecked() {
    console.log('parent view checked')
  }
}

// demo/global-state-react/src/App/Parent/Parent.tsx
import React from 'react';
import dataSource from '../dataSource';
import Demo from './Demo/Demo';
import Sibling from './Sibling/Sibling';

function Parent() {
  console.log('Parent render');

  return (
    <div style={{ border: 'solid 1px red' }}>
      Parent
      <button onClick={() => dataSource.tick()}>count {dataSource.count}</button>
      <Demo />
      <Sibling />
    </div>
  );
}

export default Parent;
