// demo/global-state-angular/src/app/parent/demo/child-b/child-b.component.ts
import { Component } from '@angular/core';
import dataSource from '~/dataSource';

@Component({
  selector: 'child-b',
  template: `
    <p>
      child-b
      <button (click)="tick()">count {{dataSource.count}}</button>
    </p>
  `,
  styles: []
})
export class ChildBComponent {
  dataSource = dataSource;

  tick() {
    this.dataSource.tick();
  }

  ngAfterViewChecked() {
    console.log('child-b view checked')
  }
}

// demo/global-state-react/src/App/Parent/Demo/ChildB/ChildB.tsx
import React, { useContext } from 'react';
// import dataSource from 'src/App/dataSource';
import { StoreBContext } from 'src/App/storeB';

function ChildB() {
  const storeb = useContext<any>(StoreBContext);

  console.log('ChildB render');
  return (
    <div>
      ChildB
      <button onClick={() => storeb.tick()}>storeb.count {storeb.data.count}</button>
    </div>
  );
}

export default ChildB;
